#!/bin/bash

printHelpMessage() {
	echo Usage: tcst \[OPTIONS\]
	echo C testing framework.
	echo Compiles and runs C files whose names begin with \"test\"
	echo then compares the output of these files with the expected
	echo output found within the check files from the given
	echo CHECK_FILE_DIRECTORY.
	echo The program will compile a file such as
	echo ./src/dir1/.../dirn/testn.c to the executable
	echo ./src/output/dir1...dirntestn, which will then be run, and
	echo its output will be compared to the contents of
	echo CHECK_FILE_DIRECTORY/dir1...dirntestn.
	echo The folder CHECK_FILE_DIRECTORY and its contents must 
	echo already be created at runtime.
	echo
	echo Options:
	echo "    -h, --help                       displays this message"
	echo "    -o, --output                     outputs expected/actual output"
	echo "                                     of executable if it fails at"
	echo "                                     runtime"
	echo "    -c, --display-compiler-errors    displays compilation errors if"
	echo "                                     any occur"
	echo "    -b, --bench-mark    <N>          run benchmark for each test N"
	echo "                                     times"
	echo "    CHECK_FILE_DIRECTORY             absolute path to the directory"
	echo "                                     containing the check files for"
	echo "                                     the tests"
	echo
	echo Exit status:
	echo 
	echo 0 if OK
	echo 1 if \"src\" directory not found
	echo 2 if not enough parameters / wrong parameters
	echo 3 if check files directory does not exist
	echo 4 if check files directory is empty
	echo 10 if some test failed
	echo 
	echo Expected directory structure:
	echo "./"
	echo "|--src"
	echo "| |--test*.c"
	echo "| | ..."
	echo "| ..."
}

benchmark() {
	echo "  "Running benchmark for $3...
	startTime=$(date +%s%3N)
	for ((i=0;i<$2;i++)) 
	do
		 $1 > /dev/null
	done
	endTime=$(date +%s%3N)
	echo "  "Benchmark time: $(($endTime-$startTime)) ms for $2 runs
}

if ! find -type d -wholename "./src" > /dev/null
then
	echo \"src\" directory not found >&2
	exit 1
fi

if [[ $# -lt 1 ]] || $([[ $# -eq 1 ]] && [[ $1 == "--help" ]] || [[ $1 == "-h" ]])
then 
	printHelpMessage 
	if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]
	then
		exit 0
	fi
	exit 2
fi

outputOnFailed=0
displayCompilerErrors=0
totalNoOfTests=0
noOfSuccessfullTests=0
checkFileDirectory=0
benchMarkCheck=0
benchMarkSize=10000
last=" "

for param in $@
do
	if [[ $param != "-h" ]] && [[ $param != "--help" ]] && [[ $param != "-o" ]] && [[ $param != "--output" ]] && [[ $param != "-c" ]] && [[ $param != "--display-compiler-errors" ]] && [[ $param != "-b" ]] && [[ $param != "--bench-mark" ]]
	then
		if [[ $param == -* ]]
		then
			printHelpMessage
			exit 2
		fi
		if [[ $last == "-b" ]] || [[ $last == "--bench-mark" ]]
		then
			benchMarkSize=$param
		else
			if [[ $checkFileDirectory == 0 ]]
			then
				checkFileDirectory=$param
			else
				printHelpMessage
				exit 2
			fi
		fi
	fi

	if [[ $param == "-b" ]] || [[ $param == "--bench-mark" ]] 
	then
		benchMarkCheck=1
	fi

	if [[ $param == "-h" ]] || [[ $param == "--help" ]]
	then
		printHelpMessage
		exit 0
	fi

	if [[ $param == "-o" ]] || [[ $param == "--output" ]]
	then 
		outputOnFailed=1
	fi

	if [[ $param == "-c" ]] || [[ $param == "--display-compiler-errors" ]]
	then
		displayCompilerErrors=1
	fi
	last=$param
done

if [[ $checkFileDirectory != */ ]]
then
	checkFileDirectory=$checkFileDirectory"/"
fi

if ! [ -d $checkFileDirectory ]
then
	echo check files directory \"$checkFileDirectory\" does not exist >&2
	exit 3
fi

if [[ $(find $checkFileDirectory -type f | wc -l) == 0 ]] 
then 
	echo check files directory \"$checkFileDirectory\" is empty >&2
	exit 4
fi

mkdir ./src/output 2> /dev/null
touch ./src/output/outputcheck 2> /dev/null

find ./src -type f -name "test*.c" | while read testFile
do
	echo 1 >> totcount

 	outputFileName=$(echo $testFile  | sed "s/.\/src\///" | sed "s/\///g" | sed "s/.c//")
	checkFile="$checkFileDirectory""$outputFileName"
	outputFileName="./src/output/$outputFileName"

	if ! gcc $testFile -o $outputFileName 2> "./src/output/compileout"
	then
		echo $testFile failed at compilation...
		if [[ $displayCompilerErrors == 1 ]]
		then
			IFS=''
			cat "./src/output/compileout" | while read line
			do
				echo "  >  "$line
			done
			echo
		fi
	else
		$outputFileName > ./src/output/outputcheck
	
		if ! [ -f $checkFile ]
		then
			echo check file for \"$testFile\" is non-existent, $testFile failed...
		else
			if cmp -s "./src/output/outputcheck" "$checkFile"
			then
				echo $testFile passed...
				if [[ $benchMarkCheck == "1" ]] 
				then 
					benchmark $outputFileName $benchMarkSize $testFile
				fi
				echo 1 >> ./succount
			else 
				echo $testFile failed at runtime...
				if [[ $outputOnFailed == "1" ]] 
				then
					echo " "Exected output for $testFile:
					cat $checkFile
					echo
					echo " "Actual output of $testFile:
					IFS=''
					cat "./src/output/outputcheck"
					echo
				fi
			fi
		fi
	fi
done

echo 
noOfSuccessfullTests=$(cat succount 2> /dev/null | wc -l)
totalNoOfTests=$(cat totcount | wc -l)
echo $noOfSuccessfullTests out of $totalNoOfTests tests passed...
rm succount totcount 2> /dev/null

if [[ $(( $totalNoOfTests - $noOfSuccessfullTests )) == 0 ]] 
then 
	exit 0
else
	exit 10
fi
